### ISSUE TITLE
The CI is broken, due to the Sphinx update

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddiparser2#106]
**Describe the bug**

Something went wrong after the last Sphinx update. This is mostly the tracker to fix this issue.

**To Reproduce**

1. Just check the CI (try out https://github.com/DiddiLeija/diddiparser2/runs/5725796950?check_suite_focus=true)
2. See the issue with `black`

**Expected behavior**

Nothing should happen after upgrading Sphinx, the CI must go well.

**Additional context**

This is the error message:

```
nox > black --check .
Traceback (most recent call last):
  File "/home/runner/work/diddiparser2/diddiparser2/.nox/lint/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "src/black/__init__.py", line 1423, in patched_main
  File "src/black/__init__.py", line 1409, in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/work/diddiparser2/diddiparser2/.nox/lint/lib/python3.9/site-packages/click/__init__.py)
nox > Command black --check . failed with exit code 1
nox > Session lint failed.
```

**Comment by DiddiLeija** [comment]
I'll try to reproduce this locally.

**Comment by DiddiLeija** [comment]
Ok, I tried this locally. I tried two scenarios.

<details>

<summary>With the current requirements</summary>

```
nox > Running session lint
nox > Creating virtual environment (virtualenv) using python.exe in .nox\lint
nox > python -m pip install -r tests/requirements.txt
nox > python -m pip install -e .
nox > flake8 . --count --show-source --statistic
0
nox > isort . --check-only -v

                 _                 _
                (_) ___  ___  _ __| |_
                | |/ _/ / _ \/ '__  _/
                | |\__ \/\_\/| |  | |_
                |_|\___/\___/\_/   \_/

      isort your imports, so you don't have to.

                    VERSION 5.10.1

else-type place_module for os returned STDLIB
else-type place_module for sys returned STDLIB
else-type place_module for time returned STDLIB
else-type place_module for nox returned THIRDPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\noxfile.py Everything Looks Good!
else-type place_module for argparse returned STDLIB
from-type place_module for diddiparser2.parser returned FIRSTPARTY
from-type place_module for diddiparser2.parser returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\cli.py Everything Looks Good!
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\diddiscript_types.py Everything Looks Good!
from-type place_module for colorama returned THIRDPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\messages.py Everything Looks Good!
else-type place_module for io returned STDLIB
else-type place_module for sys returned STDLIB
from-type place_module for diddiparser2 returned FIRSTPARTY
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.lib returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\parser.py Everything Looks Good!
from-type place_module for colorama returned THIRDPARTY
from-type place_module for diddiparser2.parser returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\__init__.py Everything Looks Good!
from-type place_module for diddiparser2.cli returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\__main__.py Everything Looks Good!
else-type place_module for json returned STDLIB
from-type place_module for tkinter returned STDLIB
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\editor\formatter.py Everything Looks Good!
else-type place_module for tkinter returned STDLIB
from-type place_module for tkinter returned STDLIB
from-type place_module for idlelib.textview returned THIRDPARTY
from-type place_module for diddiparser2 returned FIRSTPARTY
from-type place_module for diddiparser2.editor returned FIRSTPARTY
from-type place_module for diddiparser2.editor returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
from-type place_module for diddiparser2.parser returned FIRSTPARTY
from-type place_module for diddiparser2.parser returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\editor\main.py Everything Looks Good!
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\editor\__init__.py Everything Looks Good!
from-type place_module for diddiparser2.editor.main returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\editor\__main__.py Everything Looks Good!
else-type place_module for io returned STDLIB
else-type place_module for os returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\fileio.py Everything Looks Good!
else-type place_module for math returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\math.py Everything Looks Good!
else-type place_module for sys returned STDLIB
else-type place_module for time returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\simpleio.py Everything Looks Good!
else-type place_module for sqlite3 returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\sqlite.py Everything Looks Good!
else-type place_module for subprocess returned STDLIB
else-type place_module for sys returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\subprocessing.py Everything Looks Good!
else-type place_module for importlib returned STDLIB
else-type place_module for os returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.lib returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\_builtin.py Everything Looks Good!
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\__init__.py Everything Looks Good!
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\docs\conf.py Everything Looks Good!
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.lib.simpleio returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\tests\dsgp_3_example.py Everything Looks Good!
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\tests\my_extension.py Everything Looks Good!
.git was skipped as it's listed in 'skip' setting, matches a glob in 'skip_glob' setting, or is in a .gitignore file with --skip-gitignore enabled.
.nox was skipped as it's listed in 'skip' setting, matches a glob in 'skip_glob' setting, or is in a .gitignore file with --skip-gitignore enabled.
Skipped 2 files
nox > black --check .
Traceback (most recent call last):
  File "C:\Users\Diego Ramirez\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Diego Ramirez\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Diego Ramirez\diddiparser2\.nox\lint\Scripts\black.EXE\__main__.py", line 7, in <module>
  File "src\black\__init__.py", line 1423, in patched_main
  File "src\black\__init__.py", line 1409, in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (C:\Users\Diego Ramirez\diddiparser2\.nox\lint\lib\site-packages\click\__init__.py)
nox > Command black --check . failed with exit code 1
nox > Session lint failed.

C:\Users\Diego Ramirez\diddiparser2>
```

</details>

<details>
<summary>Downgrading Sphinx to 4.4.0</summary>

```
C:\Users\Diego Ramirez\diddiparser2>git checkout
M       docs/requirements.txt
Your branch is up to date with 'origin/main'.

C:\Users\Diego Ramirez\diddiparser2>nox -s lint
nox > Running session lint
nox > Creating virtual environment (virtualenv) using python.exe in .nox\lint
nox > python -m pip install -r tests/requirements.txt
nox > python -m pip install -e .
nox > flake8 . --count --show-source --statistic
0
nox > isort . --check-only -v

                 _                 _
                (_) ___  ___  _ __| |_
                | |/ _/ / _ \/ '__  _/
                | |\__ \/\_\/| |  | |_
                |_|\___/\___/\_/   \_/

      isort your imports, so you don't have to.

                    VERSION 5.10.1

else-type place_module for os returned STDLIB
else-type place_module for sys returned STDLIB
else-type place_module for time returned STDLIB
else-type place_module for nox returned THIRDPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\noxfile.py Everything Looks Good!
else-type place_module for argparse returned STDLIB
from-type place_module for diddiparser2.parser returned FIRSTPARTY
from-type place_module for diddiparser2.parser returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\cli.py Everything Looks Good!
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\diddiscript_types.py Everything Looks Good!
from-type place_module for colorama returned THIRDPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\messages.py Everything Looks Good!
else-type place_module for io returned STDLIB
else-type place_module for sys returned STDLIB
from-type place_module for diddiparser2 returned FIRSTPARTY
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.lib returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\parser.py Everything Looks Good!
from-type place_module for colorama returned THIRDPARTY
from-type place_module for diddiparser2.parser returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\__init__.py Everything Looks Good!
from-type place_module for diddiparser2.cli returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\__main__.py Everything Looks Good!
else-type place_module for json returned STDLIB
from-type place_module for tkinter returned STDLIB
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\editor\formatter.py Everything Looks Good!
else-type place_module for tkinter returned STDLIB
from-type place_module for tkinter returned STDLIB
from-type place_module for idlelib.textview returned THIRDPARTY
from-type place_module for diddiparser2 returned FIRSTPARTY
from-type place_module for diddiparser2.editor returned FIRSTPARTY
from-type place_module for diddiparser2.editor returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
from-type place_module for diddiparser2.parser returned FIRSTPARTY
from-type place_module for diddiparser2.parser returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\editor\main.py Everything Looks Good!
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\editor\__init__.py Everything Looks Good!
from-type place_module for diddiparser2.editor.main returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\editor\__main__.py Everything Looks Good!
else-type place_module for io returned STDLIB
else-type place_module for os returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\fileio.py Everything Looks Good!
else-type place_module for math returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\math.py Everything Looks Good!
else-type place_module for sys returned STDLIB
else-type place_module for time returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\simpleio.py Everything Looks Good!
else-type place_module for sqlite3 returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\sqlite.py Everything Looks Good!
else-type place_module for subprocess returned STDLIB
else-type place_module for sys returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\subprocessing.py Everything Looks Good!
else-type place_module for importlib returned STDLIB
else-type place_module for os returned STDLIB
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.lib returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\_builtin.py Everything Looks Good!
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\__init__.py Everything Looks Good!
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\docs\conf.py Everything Looks Good!
from-type place_module for diddiparser2.diddiscript_types returned FIRSTPARTY
from-type place_module for diddiparser2.lib.simpleio returned FIRSTPARTY
from-type place_module for diddiparser2.messages returned FIRSTPARTY
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\tests\dsgp_3_example.py Everything Looks Good!
SUCCESS: C:\Users\Diego Ramirez\diddiparser2\tests\my_extension.py Everything Looks Good!
.git was skipped as it's listed in 'skip' setting, matches a glob in 'skip_glob' setting, or is in a .gitignore file with --skip-gitignore enabled.
.nox was skipped as it's listed in 'skip' setting, matches a glob in 'skip_glob' setting, or is in a .gitignore file with --skip-gitignore enabled.
Skipped 2 files
nox > black --check .
Traceback (most recent call last):
  File "C:\Users\Diego Ramirez\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Diego Ramirez\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Diego Ramirez\diddiparser2\.nox\lint\Scripts\black.EXE\__main__.py", line 7, in <module>
  File "src\black\__init__.py", line 1423, in patched_main
  File "src\black\__init__.py", line 1409, in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (C:\Users\Diego Ramirez\diddiparser2\.nox\lint\lib\site-packages\click\__init__.py)
nox > Command black --check . failed with exit code 1
nox > Session lint failed.

C:\Users\Diego Ramirez\diddiparser2>
```

</details>

In both of the cases, something else is happening with the CI, is not a Sphinx issue!

**Comment by DiddiLeija** [comment]
Oh, now I get it... `click` broke something 🤦‍♂️.

**Comment by DiddiLeija** [comment]
> Oh, now I get it... `click` broke something 🤦‍♂️.

Yup, see psf/black#2964. I'll try to fix this.

**Comment by DiddiLeija** [comment]
Oh, I know how to fix this, I'll follow https://github.com/psf/black/issues/2964#issuecomment-1081035937.
