### ISSUE TITLE
Treating the current CI failure with tests

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddiparser2#151]
**Describe the bug**

Since #144, the CI has been failing. Not sure why (because I didn't make any breaking change), but that failure is a serious blocker.

**To Reproduce**

Check out the affected PRs (see below). Please check the tests CI (e.g. `Tests (ubuntu-latest, 3.10)`)

**Expected behavior**

The CI (to be precise, the tests) should not fail like that.

**Additional context**

Current list of affected PRs:

- #144
- #145
- #146
- #147
- #148 
- #149 
- #150
- #152

**Comment by DiddiLeija** [comment]
I think I've gotta remove the error handler to investigate this issue. Of course, I won't do that globally :P

**Comment by DiddiLeija** [comment]
Here comes a detailed explanation of my debugging:

<details>

First, I removed the following line (to get a clear message instead of a "weird error"):

https://github.com/DiddiLeija/diddiparser2/blob/2ade780009a157662a5d7c692820c1265805a287/diddiparser2/parser.py#L270-L271

Then I ran `nox -s tests`. The crash came from `test-dsgp3-example.diddi`:

```
nox > diddiparser2 tests/test-dsgp3-example.diddi
Traceback (most recent call last):
  File "C:\Users\Diego Ramirez\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Diego Ramirez\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Diego Ramirez\diddiparser2\.nox\tests\Scripts\diddiparser2.EXE\__main__.py", line 7, in <module>
  File "C:\Users\Diego Ramirez\diddiparser2\diddiparser2\cli.py", line 50, in main
    script.runfile()
  File "C:\Users\Diego Ramirez\diddiparser2\diddiparser2\parser.py", line 157, in runfile
    self.executeline(line)
  File "C:\Users\Diego Ramirez\diddiparser2\diddiparser2\parser.py", line 174, in executeline
    self.execute_func(line)
  File "C:\Users\Diego Ramirez\diddiparser2\diddiparser2\parser.py", line 260, in execute_func
    value = func(*fixed_args)
  File "C:\Users\Diego Ramirez\diddiparser2\diddiparser2\lib\_builtin.py", line 66, in load_extension
    ext = importlib.import_module(f"{arg}")
  File "C:\Users\Diego Ramirez\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tests'
nox > Command diddiparser2 tests/test-dsgp3-example.diddi failed with exit code 1
nox > Session tests failed.
```

Looking at the test file, the breaking line is:

https://github.com/DiddiLeija/diddiparser2/blob/2ade780009a157662a5d7c692820c1265805a287/tests/test-dsgp3-example.diddi#L10

</details>

DiddiParser will look for a `tests` local package, which doesn't exist!

**Comment by DiddiLeija** [comment]
I hope we could fix this without changing a lot of stuff :)

**Comment by DiddiLeija** [comment]
I finally found a fix. I will open a PR soon.

**Comment by DiddiLeija** [comment]
Ok, now that this issue's fixed, let's merge the affected PRs! :tada:
